name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_EZQANOON }}
          script: |
            cd /var/www/EzQanoon
            git pull origin main
            composer install --no-dev --prefer-dist
            php artisan optimize:clear
            sudo chown -R www-data:www-data /var/www/EzQanoon
            sudo chmod -R 775 /var/www/EzQanoon/storage /var/www/EzQanoon/bootstrap/cache
            sudo systemctl restart php8.4-fpm
            sudo systemctl restart nginx
